ci: add draft for running functional-tests for PRs

diff --git a/.github/workflows/functional_test_pr.yml b/.github/workflows/functional_test_pr.yml
--- a/.github/workflows/functional_test_pr.yml
+++ b/.github/workflows/functional_test_pr.yml
@@ -31,8 +31,14 @@ jobs:
           echo ${{ steps.changed-files.outputs.all_changed_files }}
         shell: bash
 
-      - name: Test Proxy-Connection
+      - name: Test Connection
         run: |
-          sudo apt install curl > /dev/null
-          https_proxy=${{ secrets.CI_TEST_PROXY }} curl https://${{ vars.CI_TEST_FIREWALL_1 }} --insecure
+          sudo apt install curl >/dev/null
+          https_proxy=${{ secrets.CI_TEST_PROXY }} curl --fail-with-body https://${{ vars.CI_TEST_FIREWALL_1 }} --insecure > /tmp/test.html
+
+          if grep -q 'DNS Rebind attack' < /tmp/test.html
+          then
+            echo 'ERROR: Firewall Hostname ${{ vars.CI_TEST_FIREWALL_1 }} not configured!'
+            exit 1
+          fi
         shell: bash
